# Generated by Django 3.2.9 on 2021-12-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20211210_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('Address', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
