# Generated by Django 3.2.9 on 2021-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='img',
            field=models.ImageField(default=True, upload_to='directory/'),
            preserve_default=False,
        ),
    ]
