# Generated by Django 3.2.9 on 2021-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_contact_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='img',
            field=models.ImageField(upload_to='directory/images'),
        ),
    ]
