# Generated by Django 3.2.9 on 2021-12-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_alter_contact_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='img',
        ),
    ]
